create table tblemployManager (id int NOT NULL, Name nvarchar(60),ManagerId int)
insert into tblemployManager values (1, 'Tom',	2)
insert into tblemployManager values (2, 'Josh',	null)
insert into tblemployManager values (3, 'Mike', 2)
insert into tblemployManager values (4, 'John', 3)
insert into tblemployManager values (5, 'Pam', 1)
insert into tblemployManager values (6, 'Marry', 3)
insert into tblemployManager values (7, 'James', 1)
insert into tblemployManager values (8, 'Sam', 5)
insert into tblemployManager values (9, 'Simon', 1)
